//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postal
    {
        public int Id { get; set; }
        public string ToName { get; set; }
        public string FromName { get; set; }
        public string ReferenceNo { get; set; }
        public string ToAddress { get; set; }
        public string FromAddress { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsReceivedMail { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
