//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        public int EmpId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public string EmpName { get; set; }
        public string EmpAddress { get; set; }
        public string EmpContactNo { get; set; }
        public string EmpGender { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
