//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleAccessLevel
    {
        public int Id { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public string PageName { get; set; }
        public Nullable<bool> AddCommand { get; set; }
        public Nullable<bool> EditCommand { get; set; }
        public Nullable<bool> DeleteCommand { get; set; }
        public Nullable<bool> ReadCommand { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
